# Important numpy questions- part1

### 1. Import numpy as np and see the version

In [1]:
import numpy as np
print(np.__version__)

1.17.4


In [6]:
#!pip install numpy --upgrade

In [7]:
#!python -m pip install --upgrade pip

In [8]:
#!pip install numpy --upgrade

### 2. How to create a 1D array?

In [9]:
ar = np.array([1,2,3])
print(ar)
print(type(ar))

[1 2 3]
<class 'numpy.ndarray'>


In [10]:
ar2 = np.arange(10)
ar2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
import random

ar3 = np.random.randint(0,10, (1,5))
print(ar3)
print(type(ar3))

[[3 0 9 6 8]]
<class 'numpy.ndarray'>


In [17]:
ar4 = np.random.rand(1,5)
print(ar4)
print(type(ar4))

[[0.28282919 0.65177476 0.8095062  0.29821655 0.89084397]]
<class 'numpy.ndarray'>


### 3. How to create a boolean array?

In [23]:
bool_ar = np.array([True, False, True], dtype=bool)
print(bool_ar)
print(type(bool_ar))

[ True False  True]
<class 'numpy.ndarray'>


In [24]:
bool_ar2 = np.full((3,3), True, dtype=bool )
bool_ar2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [25]:
bool_ar3 = np.ones((3,3), dtype=bool)
bool_ar3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 4. How to extract items that satisfy a given condition from 1D array?

In [26]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#get all odd numbers out of the array

In [27]:
[arr % 2 == 1]

[array([False,  True, False,  True, False,  True, False,  True, False,
         True])]

In [28]:
arr[[arr % 2 == 1]]

array([1, 3, 5, 7, 9])

### 5. How to replace items that satisfy a condition with another value in numpy array?

In [34]:
arr5 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr5[[arr5 % 2 == 1]] = 100

arr5

array([  0, 100,   2, 100,   4, 100,   6, 100,   8, 100])

### 6. How to replace items that satisfy a condition without affecting the original array?

In [37]:
arr6 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr5

array([  0, 100,   2, 100,   4, 100,   6, 100,   8, 100])

In [40]:
arr6_2 = np.where(arr6%2==1, 100, arr6)

arr6_2

array([  0, 100,   2, 100,   4, 100,   6, 100,   8, 100])

### 7. How to reshape an array?

In [42]:
# Q. Convert a 1D array to a 2D array with 2 rows
arr7 = np.arange(10)

arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr7.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
arr7.reshape(2, -1)  # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
arr7.reshape(5, -1)  # Setting to -1 automatically decides the number of cols

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### 8. How to stack two arrays vertically?

In [49]:
# Q. Stack arrays a and b vertically

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

a,b

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]), array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

In [53]:
#method 1
np.concatenate([a,b], axis=0)  #default axis=0,  for horizontal append use axis=1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [55]:
#method2

np.vstack([a,b])  #vstack for vertical, for rowise append use hstack

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [57]:
#method3

np.r_[a,b]  # r for appending as additional row, for append as column use np.c_

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 9. How to stack two arrays horizontally?

In [59]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1,10).reshape(2,-1)

a,b

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]), array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

In [62]:
np.concatenate([a,b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [60]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [61]:
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### 10. How to generate custom sequences in numpy without hardcoding?

In [64]:
# Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

a = np.array([1,2,3])

a

#Desired Output:
#array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

array([1, 2, 3])

In [66]:
a.repeat(3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [70]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [71]:
#note
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

### 11. How to get the common items between two python numpy arrays?

In [72]:
# Q. Get the common items between a and b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [74]:
np.intersect1d(a,b)

array([2, 4])

### 12. How to remove from one array those items that exist in another?

In [75]:
# Q. From array a remove all items present in array b

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [76]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

### 13. How to get the positions where elements of two arrays match?

In [2]:
#Q. Get the positions where elements of a and b match

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [3]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

### 14. How to extract all numbers between a given range from a numpy array?

In [4]:
# Q. Get all items between 5 and 10 from a.
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [11]:
#method1

index = np.where((a > 5) & (a < 10))
a[index]

array([6, 9])

In [12]:
#method2

index1 = np.where(np.logical_and(a>5, a<10))
a[index1]

array([6, 9])

In [10]:
#method3

a[(a>5) & (a<10)]

array([6, 9])

### 15. How to make a python function that handles scalars to work on numpy arrays?

In [13]:
#Q. Convert the function maxx that works on two scalars, to work on two arrays.

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
    
maxx(1, 5)

5

In [14]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
#pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [18]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

### 16. How to swap two columns in a 2d numpy array?

In [19]:
# Q. Swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

### 17. How to swap two rows in a 2d numpy array?

In [25]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
# to swap row - 0 and 1

arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

### 18. How to reverse the rows of a 2D array?

In [27]:
# Input
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [31]:
#example with 4x4 array

arr2 = np.arange(16).reshape(4,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
arr2[::-1]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

### 19. How to reverse the columns of a 2D array?

In [33]:
# Q. Reverse the columns of a 2D array arr.

arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### 20. How to create a 2D array containing random floats between 5 and 10?

In [35]:
# Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [40]:
#method1
arr = np.random.randint(5,10, (5,3)) + np.random.rand(5,3)
arr

array([[8.62230508, 9.35647453, 7.11217133],
       [7.19257563, 5.90348536, 9.10771153],
       [8.65670207, 9.52962425, 5.24159705],
       [7.43967437, 5.6683787 , 7.9701508 ],
       [9.43825241, 5.23615091, 9.75581275]])

In [42]:
#method2

np.random.uniform(5,10, (5,3))

array([[6.378835  , 7.15859549, 8.34113784],
       [7.83859268, 9.97997288, 8.58477958],
       [8.67128905, 8.02641874, 6.5335317 ],
       [8.15476205, 9.47761574, 6.13492261],
       [5.91862983, 5.87401116, 9.1565196 ]])

### 21. How to print only 3 decimal places in python numpy array?

In [43]:
# Q. Print or show only 3 decimal places of the numpy array rand_arr.

rand_arr = np.random.random((5,3))
rand_arr

array([[0.77489081, 0.73243537, 0.40485189],
       [0.73203938, 0.46813156, 0.16287766],
       [0.04322964, 0.46595173, 0.18232091],
       [0.12818559, 0.41016584, 0.13277449],
       [0.33707931, 0.15159503, 0.31685534]])

In [46]:
np.set_printoptions(precision=2)
rand_arr

array([[0.77, 0.73, 0.4 ],
       [0.73, 0.47, 0.16],
       [0.04, 0.47, 0.18],
       [0.13, 0.41, 0.13],
       [0.34, 0.15, 0.32]])

### 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [47]:
#Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

#input

np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.43e-04, 2.78e-04, 4.25e-04],
       [8.45e-04, 4.72e-06, 1.22e-04],
       [6.71e-04, 8.26e-04, 1.37e-04]])

In [48]:
np.set_printoptions(suppress=True, precision=6)  # precision is optional
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

### 23. How to limit the number of items printed in output of numpy array?

In [49]:
# Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

a = np.arange(15)
a

#desired output-    array([ 0,  1,  2, ..., 12, 13, 14])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

### 24. How to print the full numpy array without truncating

In [51]:
# Q. Print the full numpy array a without truncating.

np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [3]:
np.set_printoptions(threshold=None)
b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])